[package]
name = "fulaminas"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = { version = "0.15", features = ["rayon"] }
ndarray-rand = "0.14"
petgraph = "0.8.3"
rand = "0.8"
rayon = "1.11.0"
ureq = "2.10"
flate2 = "1.0"
byteorder = "1.5"
image = "0.24"
