[package]
name = "fulaminas"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = { version = "0.15", features = ["rayon"] }
ndarray-rand = "0.14"
petgraph = "0.8.3"
rand = "0.8"
rayon = "1.11.0"
